### PR TITLE
Removed patches and updated docs

### PR DESCRIPTION
**Pull request by EvanCarroll**
We had two patch sets for B::C one in Patches and RPMS (which was totally undocumented) and then that same patch set duplicated in the docker-perl-compiler repo. Now we link the two together and specify that this will not compile against system perl.

### CODE REVIEW

**Comment by atoomic** [comment]
We can remove the patches. The goal of listing the patches here was to let anyone use this version of the perl-compiler after patching Perl with the provided patches.

This is true that the docker version of Perl is using a complete patch set. But not sure it's really a duplicate, and why the listed patches here are an issue. But once again, I see no problems dropping them.

We should probably be more clear in the `README.md` about the requirement of patching Perl with the list of patches that you are now removing...

**Comment by EvanCarroll** [comment]
The exact text I added after Todd clarified what I was doing wrong is,

> Moreover, this will likely not work on system perl, as it requires Perl to be both [single
threaded and compiled with a specific patch set.](https://github.com/cpanel/docker-perl-compiler/tree/perl-v5.32.0/patches)

If the purpose of this patch set vs the one in `docker-perl-compiler` was to say that this patch set is _required_ while the other is _recommended_ then I could revert the deletions and clarify the docs. I just didn't want multiple sources of truth for the patch set if we're only supporting one of them, and provide no guidance on either.

**Comment by atoomic** [comment]
This patch set provides (or was providing) the minimal set of patches to use perl-compiler.
You cannot use the current perl-compiler without patching Perl.
The docker image used for testing is setup with a perl version customized for cPanel. (this includes this minimal list of patches among some extra).

Removing the patches from this repo, would make it impossible or harder for anyone trying to use this version of the perl-compiler.

**Comment by atoomic** [comment]
the useless patches are going to be removed in the next branch for 5.35

**Pull request closed without merging**
